### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by fflorent** [yaal-coop/scim2-tester#2]
Hello!

I saw that this repository is meant to be used for testing our own implementation.

I am not *very* familiar to python ecosystems, I see that there is a main block in `./scim2_tester/checker.py`, so we can run it directly.

I tried this, apparently I achieved to run the command this way:
```
poetry lock # Apparently the poetry.lock is outdated, is it normal?
poetry env use python3.11
poetry install
poetry run python ./scim2_tester/checker.py https://scim.example
```

**Comment by azmeuk** [comment]
Hi. This package provides methods that can be integrated in other projects, and a simple CLI with `scim2_tester/checker.py` that you found. That CLI is undocumented at the moment, but indeed it should be mentioned somewhere.
You can also use it via [scim2-cli](https://scim2-cli.readthedocs.io/), with `scim https://scim.example test` for instance.

**Comment by fflorent** [comment]
Thank you! :pray:
